// Re-export all memory types from @pyxmate/memory SDK — single source of truth
export {
  type ConsolidationRunResult,
  type ExtendedMemoryInterface,
  type GraphNode,
  type GraphTraversalResult,
  type IngestEntity,
  type IngestRelationship,
  type IngestionResult,
  type MemoryEntry,
  type MemoryIngestRequest,
  type MemoryInterface,
  type MemoryListParams,
  type MemoryListResult,
  type MemorySearchParams,
  type MemorySearchResult,
  type MemoryStats,
  MemoryType,
  RAGStrategy,
  type StoreInput,
  StoreTarget,
} from '@pyxmate/memory';
